# Capstone Project - House Price Prediction

Certain Parts like Data Cleaning, Analysis are being redacted for confidentiality reasons

# Data Modeling

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_excel(f'/content/drive/MyDrive/Capstone Project MCA-DS House Price Prediction/Datasets/cleaned_innercity.xlsx',index_col=None)
scaled_data = pd.read_excel('/content/drive/MyDrive/Capstone Project MCA-DS House Price Prediction/Datasets/scaled_data.xlsx',index_col=None)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21598 entries, 0 to 21597
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             21598 non-null  int64
 1   room_bed          21598 non-null  int64
 2   room_bath         21598 non-null  int64
 3   living_measure    21598 non-null  float64
 4   lot_measure       21598 non-null  int64
 5   ceil              21598 non-null  float64
 6   coast             21598 non-null  int64
 7   sight             21598 non-null  int64
 8   condition         21598 non-null  int64
 9   quality           21598 non-null  int64
 10  ceil_measure      21598 non-null  int64
 11  basement          21598 non-null  int64
 12  yr_built          21598 non-null  int64
 13  yr_renovated      21598 non-null  int64
 14  living_measure15  21598 non-null  int64
 15  lot_measure15     21598 non-null  int64
 16  furnished         21598 non-null  int64
 17  year              21598 non-null  int64
 18  month             21598 non-null  int64
 19  day               21598 non-null  int64
 20  age               21598 non-null  int64
 21  City              21598 non-null  object
dtypes: float64(2), int64(19), object(1)
memory usage: 3.6+ MB

In [ ]:
data.head()

,price,room_bed,room_bath,living_measure,lot_measure,ceil,coast,sight,condition,quality,...,yr_built,yr_renovated,living_measure15,lot_measure15,furnished,year,month,day,age,City
0,600000,4,1,3050.0,9440,1.0,0,0,3,8,...,1966,0,2020,8660,0,2015,4,27,49,KIRKLAND
1,190000,2,1,670.0,3101,1.0,0,0,4,6,...,1948,0,1660,4100,0,2015,3,17,67,SEATTLE
2,735000,4,2,3040.0,2415,2.0,1,4,3,8,...,1966,0,2620,2433,0,2014,8,20,49,SEATTLE
3,257000,3,2,1740.0,3721,2.0,0,0,3,8,...,2009,0,2030,3794,0,2014,10,10,6,AUBURN
4,450000,2,1,1120.0,4590,1.0,0,0,3,7,...,1924,0,1120,5100,0,2015,2,18,91,SEATTLE

In [ ]:
scaled_data.head()

,price,room_bed,room_bath,living_measure,lot_measure,ceil,coast,sight,condition,quality,ceil_measure,basement_measure,yr_built,living_measure15,lot_measure15,furnished,City
0,0.464396,1,-1,1.017857,0.324151,-0.5,0,0,0,1,0.235294,2.232143,-0.195652,0.206897,0.208835,0,12
1,-0.804954,-1,-1,-1.107143,-0.804237,-0.5,0,0,1,-1,-0.872549,0.000000,-0.586957,-0.206897,-0.706827,0,20
2,0.882353,1,0,1.008929,-0.926350,0.5,1,4,0,1,1.450980,0.000000,-0.195652,0.896552,-1.041566,0,20
3,-0.597523,0,0,-0.151786,-0.693872,0.5,0,0,0,1,0.176471,0.000000,0.739130,0.218391,-0.768273,0,0
4,0.000000,-1,-1,-0.705357,-0.539184,-0.5,0,0,0,0,-0.431373,0.000000,-1.108696,-0.827586,-0.506024,0,20

In [ ]:
features = scaled_data[['room_bed','room_bath','living_measure']]
features.head()

   room_bed  room_bath  living_measure
0         1         -1        1.017857
1        -1         -1       -1.107143
2         1          0        1.008929
3         0          0       -0.151786
4        -1         -1       -0.705357

In [ ]:
# Extract the data between the 25th and 75th percentiles
lower_bound = data['living_measure'].quantile(0.25)
upper_bound = data['living_measure'].quantile(0.75)
filtered_data = data[(data['living_measure'] >= lower_bound) & (data['living_measure'] <= upper_bound)].dropna()

# Print the extracted data
filtered_data.head()

,price,room_bed,room_bath,living_measure,lot_measure,ceil,coast,sight,condition,quality,...,yr_built,yr_renovated,living_measure15,lot_measure15,furnished,year,month,day,age,City
3,257000,3,2,1740.0,3721,2.0,0,0,3,8,...,2009,0,2030,3794,0,2014,10,10,6,AUBURN
5,245000,3,2,1610.0,7223,2.0,0,0,3,7,...,1994,0,1610,7162,0,2014,7,9,21,KENT
9,299950,2,1,1460.0,10506,1.0,0,0,3,7,...,1983,0,1460,8153,0,2014,10,28,32,KENT
11,550000,3,1,1520.0,2500,1.5,0,0,3,8,...,1912,0,1880,3600,0,2015,1,23,103,SEATTLE
12,480000,3,2,2450.0,28185,2.0,0,0,3,9,...,1990,0,2440,33541,1,2014,10,29,25,RENTON

### Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import math
from sklearn import datasets
from sklearn.model_selection import KFold, cross_val_score


# Select the features and target variable
features = scaled_data[['room_bed','room_bath','living_measure','lot_measure','ceil','condition','quality','ceil_measure','furnished']]
#features = data[['living_measure','quality','ceil_measure','living_measure15','furnished','room_bath','ceil','age']]
target = scaled_data[['price']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Create an instance of the Linear Regression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)


# Evaluate the model using mean squared error
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred)

# Calculate the root mean squared error (RMSE)
train_rmse = math.sqrt(train_mse)
test_rmse = math.sqrt(test_mse)

# Calculate the R-squared value
train_r_squared = model.score(X_train, y_train)
test_r_squared = model.score(X_test, y_test)

# Compute the adjusted R-squared
train_n = len(X_train) # Number of samples in the train set
test_n = len(X_test)  # Number of samples in the test set

p = len(features)  # Number of features

adjusted_train_r_squared = 1 - (1 - train_r_squared) * (train_n - 1) / (train_n - p - 1)
adjusted_test_r_squared = 1 - (1 - test_r_squared) * (test_n - 1) / (test_n - p - 1)


print('Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared')
print(type(model).__name__,',',train_rmse,',',test_rmse,',',adjusted_train_r_squared,',',adjusted_test_r_squared)

scores = cross_val_score(model, features, target, cv = 5)

print("Cross Validation Scores: ", scores)
print("Average CV Score: ", scores.mean())
print("Number of CV Scores used in Average: ", len(scores))

Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared
LinearRegression , 0.7569616675350598 , 0.7297776494839522 , 2.7354882310227913 , 1.1118899048060422
Cross Validation Scores:  [0.56611274 0.56712776 0.54596893 0.55071976 0.58206611]
Average CV Score:  0.5623990584411458
Number of CV Scores used in Average:  5

### Decision Tree Regression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

# Select the features and target variable
# Select the features and target variable
features = scaled_data[['room_bed','room_bath','living_measure','lot_measure','ceil','condition','quality','ceil_measure','furnished','City','living_measure15','lot_measure15']]
#features = data[['living_measure','quality','ceil_measure','living_measure15','furnished','room_bath','ceil','age']]
target = scaled_data[['price']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Create an instance of the DecisionTreeRegressor
model = DecisionTreeRegressor()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)


# Evaluate the model using mean squared error
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred)

# Calculate the root mean squared error (RMSE)
train_rmse = math.sqrt(train_mse)
test_rmse = math.sqrt(test_mse)

# Calculate the R-squared value
train_r_squared = model.score(X_train, y_train)
test_r_squared = model.score(X_test, y_test)

# Compute the adjusted R-squared
train_n = len(X_train) # Number of samples in the train set
test_n = len(X_test)  # Number of samples in the test set

p = len(features)  # Number of features

adjusted_train_r_squared = 1 - (1 - train_r_squared) * (train_n - 1) / (train_n - p - 1)
adjusted_test_r_squared = 1 - (1 - test_r_squared) * (test_n - 1) / (test_n - p - 1)


print('Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared')
print(type(model).__name__,',',train_rmse,',',test_rmse,',',adjusted_train_r_squared,',',adjusted_test_r_squared)

scores = cross_val_score(model, features, target, cv = 5)

print("Cross Validation Scores: ", scores)
print("Average CV Score: ", scores.mean())
print("Number of CV Scores used in Average: ", len(scores))

Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared
DecisionTreeRegressor , 0.02877808522305991 , 0.7759092347527646 , 1.0025084051675748 , 1.1264828460566714
Cross Validation Scores:  [0.515181   0.5097637  0.50392804 0.53142091 0.52565866]
Average CV Score:  0.5171904615465867
Number of CV Scores used in Average:  5

### Random Forest Regression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Select the features and target variable
# Select the features and target variable
features = scaled_data[['room_bed','room_bath','living_measure','lot_measure','ceil','condition','quality','ceil_measure','furnished']]
#features = data[['living_measure','quality','ceil_measure','living_measure15','furnished','room_bath','ceil','age']]
target = scaled_data[['price']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)

# Create an instance of the Random Forest Regressor model
model = RandomForestRegressor()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)


# Evaluate the model using mean squared error
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred)

# Calculate the root mean squared error (RMSE)
train_rmse = math.sqrt(train_mse)
test_rmse = math.sqrt(test_mse)

# Calculate the R-squared value
train_r_squared = model.score(X_train, y_train)
test_r_squared = model.score(X_test, y_test)

# Compute the adjusted R-squared
train_n = len(X_train) # Number of samples in the train set
test_n = len(X_test)  # Number of samples in the test set

p = len(features)  # Number of features

adjusted_train_r_squared = 1 - (1 - train_r_squared) * (train_n - 1) / (train_n - p - 1)
adjusted_test_r_squared = 1 - (1 - test_r_squared) * (test_n - 1) / (test_n - p - 1)


print('Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared')
print(type(model).__name__,',',train_rmse,',',test_rmse,',',adjusted_train_r_squared,',',adjusted_test_r_squared)

scores = cross_val_score(model, features, target, cv = 5)

print("Cross Validation Scores: ", scores)
print("Average CV Score: ", scores.mean())
print("Number of CV Scores used in Average: ", len(scores))

<ipython-input-11-d540b156c1a3>:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)

Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared
RandomForestRegressor , 0.25525294796733367 , 0.6776138195261984 , 1.1127595511735437 , 1.1683428958203086

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

Cross Validation Scores:  [0.6455556  0.5988275  0.65366854 0.61827937 0.66289571]
Average CV Score:  0.6358453450156794
Number of CV Scores used in Average:  5

### KNN Regression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

# Select the features and target variable
# Select the features and target variable
features = scaled_data[['room_bed','room_bath','living_measure','lot_measure','ceil','condition','quality','ceil_measure','furnished','City','living_measure15']]
#features = data[['living_measure','quality','ceil_measure','living_measure15','furnished','room_bath','ceil','age']]
target = scaled_data[['price']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Create an instance of the KNeighborsRegressor model
model = KNeighborsRegressor(n_neighbors = 6)

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)


# Evaluate the model using mean squared error
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred)

# Calculate the root mean squared error (RMSE)
train_rmse = math.sqrt(train_mse)
test_rmse = math.sqrt(test_mse)

# Calculate the R-squared value
train_r_squared = model.score(X_train, y_train)
test_r_squared = model.score(X_test, y_test)

# Compute the adjusted R-squared
train_n = len(X_train) # Number of samples in the train set
test_n = len(X_test)  # Number of samples in the test set

p = len(features)  # Number of features

adjusted_train_r_squared = 1 - (1 - train_r_squared) * (train_n - 1) / (train_n - p - 1)
adjusted_test_r_squared = 1 - (1 - test_r_squared) * (test_n - 1) / (test_n - p - 1)


print('Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared')
print(type(model).__name__,',',train_rmse,',',test_rmse,',',adjusted_train_r_squared,',',adjusted_test_r_squared)

scores = cross_val_score(model, features, target, cv = 5)

print("Cross Validation Scores: ", scores)
print("Average CV Score: ", scores.mean())
print("Number of CV Scores used in Average: ", len(scores))

Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared
KNeighborsRegressor , 0.49867869867750175 , 0.5571068882856415 , 1.7532090560958062 , 1.0652058925918633
Cross Validation Scores:  [0.7317144  0.74579207 0.71880971 0.72409877 0.7543173 ]
Average CV Score:  0.7349464510553357
Number of CV Scores used in Average:  5


### ANN Regression

In [ ]:
#!pip install tensorflow
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense



# Select the features and target variable
features = scaled_data[['room_bed','room_bath','living_measure','lot_measure','ceil','condition','quality','ceil_measure','furnished','City','living_measure15','lot_measure15','sight']]
#features = data[['living_measure','quality','ceil_measure','living_measure15','furnished','room_bath','ceil','age']]
target = scaled_data[['price']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Scale the features using Min-Max scaling
# scaler = MinMaxScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# Create the ANN model
model = Sequential()
model.add(Dense(32, activation='relu'))#, input_shape=(len(features),)))
model.add(Dense(16, activation='relu'))
model.add(Dense(1))

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the model using mean squared error
mse = np.mean((y_pred - y_test) ** 2)

# Make predictions on the testing data
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)


# Evaluate the model using mean squared error
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred)

# Calculate the root mean squared error (RMSE)
train_rmse = math.sqrt(train_mse)
test_rmse = math.sqrt(test_mse)

# Calculate the R-squared value
# train_r_squared = model.score(X_train, y_train)
# test_r_squared = model.score(X_test, y_test)
train_r_squared = r2_score(y_train,y_pred_train)
test_r_squared = r2_score(y_test,y_pred)


# Compute the adjusted R-squared
train_n = len(X_train) # Number of samples in the train set
test_n = len(X_test)  # Number of samples in the test set

p = len(features)  # Number of features

adjusted_train_r_squared = 1 - (1 - train_r_squared) * (train_n - 1) / (train_n - p - 1)
adjusted_test_r_squared = 1 - (1 - test_r_squared) * (test_n - 1) / (test_n - p - 1)


print('Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared')
print(type(model).__name__,',',train_rmse,',',test_rmse,',',adjusted_train_r_squared,',',adjusted_test_r_squared)

Epoch 1/50
540/540 [==============================] - 2s 2ms/step - loss: 2.2458
Epoch 2/50
540/540 [==============================] - 1s 2ms/step - loss: 0.4705
Epoch 3/50
540/540 [==============================] - 1s 2ms/step - loss: 0.4386
Epoch 4/50
540/540 [==============================] - 1s 2ms/step - loss: 0.4111
Epoch 5/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3988
Epoch 6/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3940
Epoch 7/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3823
Epoch 8/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3790
Epoch 9/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3719
Epoch 10/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3649
Epoch 11/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3647
Epoch 12/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3645
Epoch 13/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3620
Epoch 14/50
540/540 [==============================] - 2s 3ms/step - loss: 0.3516
Epoch 15/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3503
Epoch 16/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3513
Epoch 17/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3488
Epoch 18/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3423
Epoch 19/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3346
Epoch 20/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3341
Epoch 21/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3285
Epoch 22/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3302
Epoch 23/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3315
Epoch 24/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3251
Epoch 25/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3226
Epoch 26/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3223
Epoch 27/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3140
Epoch 28/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3184
Epoch 29/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3144
Epoch 30/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3125
Epoch 31/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3098
Epoch 32/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3118
Epoch 33/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3095
Epoch 34/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3073
Epoch 35/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3052
Epoch 36/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3038
Epoch 37/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3037
Epoch 38/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3026
Epoch 39/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2991
Epoch 40/50
540/540 [==============================] - 1s 2ms/step - loss: 0.3020
Epoch 41/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2948
Epoch 42/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2941
Epoch 43/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2961
Epoch 44/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2935
Epoch 45/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2944
Epoch 46/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2931
Epoch 47/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2917
Epoch 48/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2895
Epoch 49/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2870
Epoch 50/50
540/540 [==============================] - 1s 2ms/step - loss: 0.2948
135/135 [==============================] - 0s 1ms/step
 38/540 [=>............................] - ETA: 0s

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

540/540 [==============================] - 1s 1ms/step
135/135 [==============================] - 0s 1ms/step
Model,Train RMSE, Test RMSE, Train Adj R-squared,Test Adj R-squared
Sequential , 0.5232465014425788 , 0.5625713083238869 , 1.829252070386353 , 1.0664913186043972

In [ ]:
# scores = cross_val_score(model, features, target, cv = 5)
score = model.evaluate(X_test,y_test,verbose=0)
score_train = model.evaluate(X_train,y_train,verbose=0)

print("Total Loss Test: ", score)
print("Total Loss Train: ", score_train)
#print("Average CV Score: ", scores.mean())
#print("Number of CV Scores used in Average: ", len(scores))
#print("MSE : ",mse)

Total Loss Test:  0.3164864778518677
Total Loss Train:  0.27378687262535095

#Boosting Algorithms

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.compose import TransformedTargetRegressor
from sklearn.preprocessing import QuantileTransformer
from sklearn.metrics import mean_squared_error,mean_absolute_error
import numpy as np
import pandas as pd
import lightgbm as lgbm
import xgboost as xg
def boost_models(x):
    #transforming target variable through quantile transformer
    regr_trans = TransformedTargetRegressor(regressor=x, transformer=QuantileTransformer(output_distribution='normal'))
    regr_trans.fit(X_train, y_train)
    yhat = regr_trans.predict(X_test)
    algoname= x.__class__.__name__
    return algoname, round(r2_score(y_test, yhat),3), round(mean_absolute_error(y_test, yhat),2), round(np.sqrt(mean_squared_error(y_test, yhat)),2)

In [ ]:
algo=[GradientBoostingRegressor(), lgbm.LGBMRegressor(), xg.XGBRFRegressor()]
score=[]
for i in algo:
    score.append(boost_models(i))

 #Collate all scores in a table
pd.DataFrame(score, columns=['Model', 'Score', 'MAE', 'RMSE'])

                       Model  Score   MAE  RMSE
0  GradientBoostingRegressor  0.698  0.33  0.60
1              LGBMRegressor  0.808  0.28  0.48
2             XGBRFRegressor  0.585  0.39  0.70

#Model Tuning

##Hyperparameter Tuning

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import KFold

cv_method = RepeatedStratifiedKFold(n_splits=5,
                                    n_repeats=3,
                                    random_state=999)


# Define our candidate hyperparameters
hp_candidates = [{'n_neighbors': [6,9,15,20,23]}]

# Search for best hyperparameters
grid = GridSearchCV(estimator=KNeighborsRegressor(),
                      param_grid=hp_candidates,
                      cv=5,
                      verbose=2,
                      scoring='r2',
                      return_train_score=True)

grid.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ......................................n_neighbors=6; total time=   0.3s
[CV] END ......................................n_neighbors=6; total time=   0.3s
[CV] END ......................................n_neighbors=6; total time=   0.2s
[CV] END ......................................n_neighbors=6; total time=   0.2s
[CV] END ......................................n_neighbors=6; total time=   0.3s
[CV] END ......................................n_neighbors=9; total time=   0.3s
[CV] END ......................................n_neighbors=9; total time=   0.3s
[CV] END ......................................n_neighbors=9; total time=   0.4s
[CV] END ......................................n_neighbors=9; total time=   0.4s
[CV] END ......................................n_neighbors=9; total time=   0.5s
[CV] END .....................................n_neighbors=15; total time=   0.3s
[CV] END .....................................n_neighbors=15; total time=   0.3s
[CV] END .....................................n_neighbors=15; total time=   0.3s
[CV] END .....................................n_neighbors=15; total time=   0.3s
[CV] END .....................................n_neighbors=15; total time=   0.3s
[CV] END .....................................n_neighbors=20; total time=   0.3s
[CV] END .....................................n_neighbors=20; total time=   0.4s
[CV] END .....................................n_neighbors=20; total time=   0.5s
[CV] END .....................................n_neighbors=20; total time=   0.3s
[CV] END .....................................n_neighbors=20; total time=   0.4s
[CV] END .....................................n_neighbors=23; total time=   0.4s
[CV] END .....................................n_neighbors=23; total time=   0.4s
[CV] END .....................................n_neighbors=23; total time=   0.3s
[CV] END .....................................n_neighbors=23; total time=   0.4s
[CV] END .....................................n_neighbors=23; total time=   0.4s

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid=[{'n_neighbors': [6, 9, 15, 20, 23]}],
             return_train_score=True, scoring='r2', verbose=2)

In [ ]:
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

0.7217151877231734
{'n_neighbors': 9}
KNeighborsRegressor(n_neighbors=9)

##Light Gradient Boosting Algorithm with tuned params

In [ ]:
param_grid = {
    'num_leaves': [31, 127],
    'reg_alpha': [0.1, 0.5],
    'min_data_in_leaf': [30, 50, 100, 300, 400],
    'lambda_l1': [0, 1, 1.5],
    'lambda_l2': [0, 1]
    }


gsearch = GridSearchCV(estimator=lgbm.LGBMRegressor(), param_grid=param_grid, cv=10)
lgb_model = gsearch.fit(X=X_train, y=y_train)

print(lgb_model.best_params_, lgb_model.best_score_)

In [ ]:
import pickle
with open('/content/drive/MyDrive/Capstone Project MCA-DS House Price Prediction/Interim Report/lgbmmodel.pkl','rb') as f:
  lgb_model = pickle.load(f)

In [ ]:
print(lgb_model.best_score_,lgb_model.best_estimator_)

0.7620768643552179 LGBMRegressor(lambda_l1=1.5, lambda_l2=0, min_data_in_leaf=30, reg_alpha=0.1)

#Feature Engineering

In [ ]:
features = ['price','living_measure','lot_measure','ceil_measure','living_measure15','lot_measure15','basement_measure']

In [ ]:
lower_bound = scaled_data['living_measure'].quantile(0.25)
upper_bound = scaled_data['living_measure'].quantile(0.75)
filtered_data = scaled_data[(scaled_data['living_measure'] >= lower_bound) & (scaled_data['living_measure'] <= upper_bound)]

In [ ]:
filtered_data = scaled_data.copy()

In [ ]:
for i in features:
    q25, q75 = np.quantile(filtered_data[i], 0.10), np.quantile(filtered_data[i], 0.85)
    # calculate the IQR
    iqr = q75 - q25
    # calculate the outlier cutoff
    cut_off = iqr * 1.5
    # calculate the lower and upper bound value
    lower, upper = q25 - cut_off, q75 + cut_off
    filtered_data = filtered_data[(filtered_data[i] >= lower) & (filtered_data[i] <= upper)]
    df1 = scaled_data[scaled_data[i] > upper]
    df2 = scaled_data[scaled_data[i] < lower]
    print('Total number of outliers in '+i+' are', df1.shape[0]+ df2.shape[0])

Total number of outliers in price are 451
Total number of outliers in living_measure are 109
Total number of outliers in lot_measure are 1657
Total number of outliers in ceil_measure are 115
Total number of outliers in living_measure15 are 92
Total number of outliers in lot_measure15 are 1812
Total number of outliers in basement_measure are 77

In [ ]:
filtered_data.describe()

,price,room_bed,room_bath,living_measure,lot_measure,ceil,coast,sight,condition,quality,ceil_measure,basement_measure,yr_built,living_measure15,lot_measure15,furnished,City
count,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000,19115.000000
mean,0.129219,0.332043,-0.307193,0.040449,-0.003205,-0.015982,0.002563,0.185456,0.408632,0.527544,0.117631,0.491521,-0.106749,0.065284,-0.061213,0.155061,15.166623
std,0.765892,0.892387,0.671555,0.678817,0.742905,0.543512,0.050567,0.666056,0.650302,1.035881,0.688630,0.727844,0.650570,0.695428,0.689714,0.361973,6.601983
min,-1.151703,-3.000000,-2.000000,-1.375000,-1.263673,-0.500000,0.000000,0.000000,-2.000000,-4.000000,-1.166667,0.000000,-1.630435,-1.586207,-1.399398,0.000000,0.000000
25%,-0.424906,0.000000,-1.000000,-0.464286,-0.481955,-0.500000,0.000000,0.000000,0.000000,0.000000,-0.392157,0.000000,-0.543478,-0.436782,-0.526104,0.000000,11.000000
50%,-0.046440,0.000000,0.000000,-0.062500,-0.074051,-0.500000,0.000000,0.000000,0.000000,0.000000,-0.058824,0.000000,-0.065217,-0.068966,-0.073896,0.000000,19.000000
75%,0.492260,1.000000,0.000000,0.446429,0.335099,0.500000,0.000000,0.000000,1.000000,1.000000,0.490196,0.964286,0.478261,0.448276,0.299598,0.000000,20.000000
max,3.498452,8.000000,5.000000,3.223214,4.138668,2.000000,1.000000,4.000000,2.000000,5.000000,3.098039,3.571429,0.869565,3.068966,2.737952,1.000000,23.000000

In [ ]:
scaled_data.describe()

,price,room_bed,room_bath,living_measure,lot_measure,ceil,coast,sight,condition,quality,ceil_measure,basement_measure,yr_built,living_measure15,lot_measure15,furnished,City
count,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000,21598.000000
mean,0.279407,0.368367,-0.248819,0.151962,1.330788,-0.004028,0.007454,0.233818,0.407677,0.657052,0.224186,0.520593,-0.086685,0.167886,1.032750,0.196546,14.916705
std,1.137632,0.906452,0.733600,0.819829,7.369226,0.539741,0.086018,0.765669,0.649882,1.175698,0.812003,0.790257,0.638576,0.785305,5.477564,0.397395,6.765471
min,-1.160991,-3.000000,-2.000000,-1.446429,-1.263673,-0.500000,0.000000,0.000000,-2.000000,-6.000000,-1.245098,0.000000,-1.630435,-1.656322,-1.399398,0.000000,0.000000
25%,-0.396285,0.000000,-1.000000,-0.428571,-0.458547,-0.500000,0.000000,0.000000,0.000000,0.000000,-0.362745,0.000000,-0.521739,-0.402299,-0.506024,0.000000,11.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000
75%,0.603715,1.000000,0.000000,0.571429,0.541453,0.500000,0.000000,0.000000,1.000000,1.000000,0.637255,1.000000,0.478261,0.597701,0.493976,0.000000,20.000000
max,22.445820,8.000000,6.000000,10.383929,292.597570,2.000000,1.000000,4.000000,2.000000,6.000000,7.696078,8.607143,0.869565,5.022989,173.409639,1.000000,23.000000

In [ ]:
data.head()

,price,room_bed,room_bath,living_measure,lot_measure,ceil,coast,sight,condition,quality,...,yr_built,yr_renovated,living_measure15,lot_measure15,furnished,year,month,day,age,City
0,600000,4,1,3050.0,9440,1.0,0,0,3,8,...,1966,0,2020,8660,0,2015,4,27,49,KIRKLAND
1,190000,2,1,670.0,3101,1.0,0,0,4,6,...,1948,0,1660,4100,0,2015,3,17,67,SEATTLE
2,735000,4,2,3040.0,2415,2.0,1,4,3,8,...,1966,0,2620,2433,0,2014,8,20,49,SEATTLE
3,257000,3,2,1740.0,3721,2.0,0,0,3,8,...,2009,0,2030,3794,0,2014,10,10,6,AUBURN
4,450000,2,1,1120.0,4590,1.0,0,0,3,7,...,1924,0,1120,5100,0,2015,2,18,91,SEATTLE

In [ ]:
features = filtered_data[['room_bed','room_bath','living_measure','lot_measure','ceil','condition','quality','ceil_measure','furnished','City','living_measure15','sight','basement_measure']]
features["age"] = data["age"]
target = filtered_data[['price']]

<ipython-input-45-26bd9ebb76c8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features["age"] = data["age"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [ ]:
lg = lgbm.LGBMRegressor(lambda_l1=1.5, lambda_l2=0, min_data_in_leaf=30, reg_alpha=0.1)
lg.fit(X_train,y_train)

[LightGBM] [Warning] lambda_l1 is set=1.5, reg_alpha=0.1 will be ignored. Current value: lambda_l1=1.5
[LightGBM] [Warning] min_data_in_leaf is set=30, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=30
[LightGBM] [Warning] lambda_l2 is set=0, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0

LGBMRegressor(lambda_l1=1.5, lambda_l2=0, min_data_in_leaf=30, reg_alpha=0.1)

In [ ]:
print("Train score for LGBM Regressor: ",lg.score(X_train,y_train))
print("Test score for LGBM Regressor: ",lg.score(X_test,y_test))

Train score for LGBM Regressor:  0.844346090712069
Test score for LGBM Regressor:  0.8006798041122201